routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
});

Auth::routes();

Route::resource('app', 'AppController');

Route::get('/search', 'SearchController@apartments')
    ->name('search');

Route::middleware(['auth', 'owner'])->group(function () {


    Route::resource('apartments', 'ApartmentsController');

    Route::resource('rooms', 'RoomsController');

    Route::get('rooms/create/{id?}', 'RoomsController@create')
        ->name('rooms.create');

    Route::resource('rent', 'RentController');

    Route::get('rent/create/{id}', 'RentController@create')
        ->name('rent.create');

    Route::resource('note', 'NoteController');

    Route::resource('finance', 'FinanceController');
});

Route::middleware(['auth'])->group(function () {
    Route::resource('home', 'HomeController');
    Route::resource('forum', 'ForumController');
    Route::get('forum/tenant/{id}', 'ForumController@tenant')
        ->name('forum.tenant');
});

app/Rent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rent extends Model
{
    protected $fillable = ['owner_id', 'tenant_id','apartment_id','room_id', 'rental_price', 'fees', 'contract_to', 'notes'];

    public function tenant()
    {
        return $this->belongsTo(User::class, 'tenant_id');
    }

    public function apartment()
    {
        return $this->belongsTo(Apartment::class, 'apartment_id');
    }

}

app/Http/Controllers/RentController.php
<?php

namespace App\Http\Controllers;

use App\Apartment;
use App\Rent;
use App\Room;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RentController extends Controller
{
    public function index()
    {
        $apartments = Apartment::all()->where('owner_id', Auth::id());
        return view('rent.index', compact('apartments'));
    }

    public function create($id)
    {
        $rooms = Room::all()->where('apartment_id', $id);
        return view('rent.create', compact('rooms'));
    }

    public function store(Request $request)
    {
        $tenant = User::find($request->tenant_id);
        $owner_id =  Auth::id();

        if (!isset($tenant)) {
            return redirect()->back()
                ->with('error', 'Dane najemcy się nie zgadzają.');
        }

        //Sprawdź zgodność podanych danych z danymi z db
        if ($request->tenant_name !== $tenant->name) {
            return redirect()->back()
                ->with('error', 'Dane najemcy się nie zgadzają.');
        }

        $apartment_id = Room::all()->where('id', $request->room_id)->first()->apartment_id;

        Rent::create([
            'owner_id' => $owner_id,
            'tenant_id' => $request->tenant_id,
            'apartment_id' => $apartment_id,
            'room_id' => $request->room_id,
            'rental_price' => $request->rental_price,
            'fees' => $request->fees,
            'contract_to' =>$request->contract_to,
            'notes' => $request->notes
        ]);


        return redirect()->route('apartments.index')
            ->with('success', 'Mieszkanie dodane pomyślnie.');
    }
}

resources/views/rent/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h5>przypisywanie najemcy do pokoju</h5>
                </div>
                <div class="card-body">
                    <form action="{{route('rent.store')}}" method="post" enctype="multipart/form-data">
                        @csrf

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Pokoje</label>
                                <select class="custom-select" id="room_id" name="room_id">
                                    @foreach($rooms as $room)
                                        <option value="{{$room->id}}">
                                            {{$room->title}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-3 mb-3">
                                <label for="title">ID najemcy</label>
                                <input type="text" class="form-control" id="tenant_id" name="tenant_id"
                                       value="{{ old('tenant_id') }}"
                                       placeholder="13">
                            </div>
                            <div class="col-md-9 mb-3">
                                <label for="title">imię i nazwisko najemcy</label>
                                <input type="text" class="form-control" id="tenant_name" name="tenant_name"
                                       value="{{ old('tenant_name') }}"
                                       placeholder="Jarek Kowalski">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-4 mb-3">
                                <label for="title">Cena za wynajem</label>
                                <input type="text" class="form-control" id="rental_price" name="rental_price"
                                       value="{{ old('rental_price') }}"
                                       placeholder="800">
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="title">Cena za media</label>
                                <input type="text" class="form-control" id="fees" name="fees"
                                       value="{{ old('fees') }}"
                                       placeholder="100">
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="title">Umowa do</label>
                                <input type="date" class="form-control" id="contract_to" name="contract_to"
                                       value="{{ old('contract_to') }}"
                                       placeholder="21.01.2020">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Notatki</label>
                                <input id="notes" type="hidden" name="notes">
                                <trix-editor input="notes">{!! old('notes') !!}</trix-editor>
                            </div>
                        </div>

                        <div class="form-group text-center my-5">
                            <button class="btn btn-success btn-block" type="submit">dodaj najemcę</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/rent/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row text-center">
        <div class="col-12">
            <h4>Wybierz pokój:</h4>
            <ul class="list-group text-center mt-3">
                @forelse($apartments as $apartment)

                    <li class="list-group-item bg-light font-weight-bold">
                        <a href="{{route('forum.show', $apartment->id)}}">{{$apartment->title}}</a>
                    </li>

                    @foreach($apartment->rooms as $room)

                        <li class="list-group-item ">
                            <a href="{{route('rent.create', $room->id)}}">{{$room->id}}. {{$room->title}}</a>
                        </li>

                    @endforeach

                @empty
                    <li class="list-group-item bg-light">
                        <h6>Dodaj mieszkanie, aby móc korzystać z forum</h6>
                    </li>
                @endforelse

            </ul>
        </div>
    </div>
@endsection