routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
});

Auth::routes();

Route::resource('app', 'AppController');

Route::get('/search', 'SearchController@apartments')
    ->name('search');

Route::middleware(['auth', 'owner'])->group(function () {


    Route::resource('apartments', 'ApartmentsController');

    Route::resource('rooms', 'RoomsController');

    Route::get('rooms/create/{id?}', 'RoomsController@create')
        ->name('rooms.create');

    Route::resource('rent', 'RentController');

    Route::get('rent/create/{id}', 'RentController@create')
        ->name('rent.create');

    Route::resource('note', 'NoteController');

    Route::resource('finance', 'FinanceController');
});

Route::middleware(['auth'])->group(function () {
    Route::resource('home', 'HomeController');
    Route::resource('forum', 'ForumController');
    Route::get('forum/tenant/{id}', 'ForumController@tenant')
        ->name('forum.tenant');
});

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $fillable = ['title', 'owner_id', 'apartment_id',
        'number_of_beds', 'rental_price', 'fees', 'description', 'img'];

    public function apartment()
    {
        return $this->belongsTo(Apartment::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'owner_id');
    }
}

app/Http/Controllers/RoomsController.php
<?php

namespace App\Http\Controllers;

use App\Apartment;
use App\Rent;
use App\Room;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RoomsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rooms = Room::all()->where('owner_id', Auth::id());
        return view('rooms.index', compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id = null)
    {
        if ($id !== null) {
            $apartments = Apartment::findOrFail($id);
        } else {
            $apartments = Apartment::all()->where('owner_id', Auth::id());
        }

        return view('rooms.create', compact('apartments', 'id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $img = (isset($request->img) ? $request->img->store('rooms') : null);

        $owner_id = Auth::id();

        Room::create([
            'title' => $request->title,
            'owner_id' => $owner_id,
            'apartment_id' => $request->apartment_id,
            'number_of_beds' => $request->number_of_beds,
            'rental_price' => $request->rental_price,
            'fees' => $request->fees,
            'description' => $request->description,
            'img' => $img,
        ]);

        return redirect()->route('apartments.index')
            ->with('success', 'Pokój dodany pomyślnie.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Room $room)
    {
        $rent = Rent::where('room_id', $room->id)->firstOrFail();
        return view('rooms.show', compact('room', 'rent'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {
        $apartments = Apartment::all()->where('owner_id', Auth::id());
        return view('rooms.edit', compact('apartments', 'room'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        dd($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/rooms/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h5>dodawanie nowego pokoju</h5>
                </div>
                <div class="card-body">
                    <form action="{{route('rooms.store')}}" method="post" enctype="multipart/form-data">
                        @csrf

                        @if($id !== null)
                            <div class="form-row">
                                <div class="col-md-12 mb-3">
                                    <label for="title">Mieszkanie</label>
                                    <select class="custom-select" id="apartment_id" name="apartment_id">
                                        <option value="{{$apartments->id}}">
                                            {{$apartments->title}}
                                        </option>
                                    </select>
                                </div>
                            </div>
                        @else
                            <div class="form-row">
                                <div class="col-md-12 mb-3">
                                    <label for="title">Mieszkanie</label>
                                    <select class="custom-select" id="apartment_id" name="apartment_id">
                                        @foreach($apartments as $apartment)
                                            <option value="{{$apartment->id}}">
                                                {{$apartment->title}}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endif

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Tytuł</label>
                                <input type="text" class="form-control" id="title" name="title"
                                       value="{{ old('title') }}"
                                       placeholder="Pokój dla dwóch osób, od strony wschodniej">
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="col-md-3 mb-3">
                                <label for="title">Ilość łóżek</label>
                                <input type="text" class="form-control" id="number_of_beds" name="number_of_beds"
                                       value="{{ old('number_of_beds') }}"
                                       placeholder="2">
                            </div>
                            <div class="col-md-4 offset-1 mb-3">
                                <label for="title">Cena za wynajem</label>
                                <input type="text" class="form-control" id="rental_price" name="rental_price"
                                       value="{{ old('rental_price') }}"
                                       placeholder="800">
                            </div>
                            <div class="col-md-3 offset-1 mb-3">
                                <label for="title">Cena za media</label>
                                <input type="text" class="form-control" id="fees" name="fees"
                                       value="{{ old('fees') }}"
                                       placeholder="100">
                            </div>
                        </div>

                        <div>
                            <label for="title">Dodaj zdjęcie</label>

                            <div class="form-row mb-3">

                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="img" id="img">
                                        <label class="custom-file-label" for="img">zdjęcie pokoju</label>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Opis</label>
                                <input id="description" type="hidden" name="description">
                                <trix-editor input="description">{!! old('description') !!}</trix-editor>
                            </div>
                        </div>

                        <div class="form-group text-center my-5">
                            <button class="btn btn-success btn-block" type="submit">dodaj pokój</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/rooms/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h5>edytowanie pokoju</h5>
                </div>
                <div class="card-body">

                    <form action="{{route('rooms.update', $room->id)}}" method="post"
                          enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Mieszkanie</label>
                                <select class="custom-select" id="apartment" name="apartment">
                                    @foreach($apartments as $apartment)
                                        <option value="{{$apartment->id}}">
                                            {{$apartment->title}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Tytuł</label>
                                <input type="text" class="form-control" id="title" name="title"
                                       value="{{old('title') ?? $room->title}}"
                                       placeholder="Pokój dla dwóch osób, od strony wschodniej">
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="col-md-3 mb-3">
                                <label for="title">Ilość łóżek</label>
                                <input type="text" class="form-control" id="number_of_beds" name="number_of_beds"
                                       value="{{old('number_of_beds') ?? $room->number_of_beds}}"
                                       placeholder="2">
                            </div>
                            <div class="col-md-4 offset-1 mb-3">
                                <label for="title">Cena za wynajem</label>
                                <input type="text" class="form-control" id="rental_price" name="rental_price"
                                       value="{{old('rental_price') ?? $room->rental_price}}"
                                       placeholder="800">
                            </div>
                            <div class="col-md-3 offset-1 mb-3">
                                <label for="title">Cena za media</label>
                                <input type="text" class="form-control" id="fees" name="fees"
                                       value="{{old('fees') ?? $room->fees}}"
                                       placeholder="100">
                            </div>
                        </div>

                        <div>
                            <label for="title">Dodaj zdjęcie</label>

                            <div class="form-row mb-3">

                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="img_1" id="img_1">
                                        <label class="custom-file-label" for="img_1">zdjęcie pokoju</label>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Opis</label>
                                <input id="description" type="hidden" name="description">
                                <trix-editor input="description">{!! old('description') ?? $room->description !!}</trix-editor>
                            </div>
                        </div>

                        <div class="form-group text-center my-5">
                            <button class="btn btn-success btn-block" type="submit">zapisz zmiany</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/rooms/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            @forelse($rooms as $room)
                <div
                    class="pl-2 no-gutters border flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="row">

                        <div class="p-4 d-flex flex-column position-static {{($room->img) ? 'col-7' : 'col-12'}}">
                            <strong class="d-inline-block text-primary"><h4>{{$room->city}} {{$room->street}}</h4>
                            </strong>
                            <div class="text-muted small">{{$room->created_at}}</div>
                            <h4 class="mt-3">{{$room->title}}</h4>
                            <p class="card-text mb-auto">{!!  $room->description !!}</p>
                            <a href="{{route('rooms.show', $room->id)}}">
                                <button type="button" class="btn btn-outline-primary btn-block   px-1">szczegóły</button>
                            </a>
                        </div>
                        @if($room->img)
                            <div class="col-5 d-none d-lg-block">
                                <div class="mt-5 p-3">
                                    <img src="{{ asset('storage/'. $room->img)}}" class="img-fluid">
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            @empty
            @endforelse
        </div>
    </div>
@endsection

resources/views/rooms/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h6>Numer ogłoszenia: {{$room->id}}</h6>
                    <h6>Najemca: {{$rent->tenant->name}}</h6>
                    <h6>Numer telefonu: {{$rent->tenant->phone_number}}</h6>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">

                        <li class="list-group-item d-flex justify-content-between">
                            <span>
                                <span>Umowa do:</span>
                                <span class="font-weight-bold">{{$rent->contract_to}}</span>
                            </span>
                            <span>
                                <span>Umowa od:</span>
                                <span class="font-weight-bold">{{$rent->created_at}}</span>
                            </span>
                        </li>

                        <li class="list-group-item">
                            <span>Tytuł:</span>
                            <span class="font-weight-bold">{{$room->title}}</span>
                        </li>

                        <li class="list-group-item">
                            <span>Mieszkanie:</span>
                            <span class="font-weight-bold">{{$room->apartment->title}}</span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between">
                            <span>
                                <span>Ilość łóżek:</span>
                                <span class="font-weight-bold">{{$room->number_of_beds}}</span>
                            </span>
                            <span>
                                <span>Cena wynajmu (za całość):</span>
                                <span class="font-weight-bold">{{$rent->rental_price}}</span>
                            </span>
                            <span>
                                <span>Opłaty:</span>
                                <span class="font-weight-bold">{{$rent->fees}}</span>
                            </span>
                        </li>

                        <li class="list-group-item ">
                            <h6>Notatki dotyczące umowy:</h6>
                            <p>{{$rent->notes}}</p>
                        </li>

                        <li class="list-group-item">
                            <div class="mt-5">
                                <img src="{{ asset('storage/'. $room->img)}}" class="img-fluid" alt="zdjęcie pokoju">
                            </div>
                        </li>

                        <li class="list-group-item">
                            <span>Opis:</span>
                            <span class="font-weight-bold">{!! $room->description !!}</span>
                        </li>

                        <li class="list-group-item">
                            <span>Dodano:</span>
                            <span class="font-weight-bold">{{ $room->created_at }}</span>
                        </li>


                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection