routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
});

Auth::routes();

Route::resource('app', 'AppController');

Route::get('/search', 'SearchController@apartments')
    ->name('search');

Route::middleware(['auth', 'owner'])->group(function () {


    Route::resource('apartments', 'ApartmentsController');

    Route::resource('rooms', 'RoomsController');

    Route::get('rooms/create/{id?}', 'RoomsController@create')
        ->name('rooms.create');

    Route::resource('rent', 'RentController');

    Route::get('rent/create/{id}', 'RentController@create')
        ->name('rent.create');

    Route::resource('note', 'NoteController');

    Route::resource('finance', 'FinanceController');
});

Route::middleware(['auth'])->group(function () {
    Route::resource('home', 'HomeController');
    Route::resource('forum', 'ForumController');
    Route::get('forum/tenant/{id}', 'ForumController@tenant')
        ->name('forum.tenant');
});

app/Apartment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Apartment extends Model
{
    protected $fillable = ['title', 'owner_id', 'city', 'street', 'apartment_number',
        'number_of_beds', 'rental_price', 'fees', 'description',
        'img_1', 'img_2', 'img_3', 'img_4'];

    public function deleteImage($img)
    {
        Storage::delete($img);
    }

    public function owner()
    {
        return $this->belongsTo(User::class);
    }

    public function rooms()
    {
        return $this->hasMany(Room::class);
    }

    public function finances()
    {
        return $this->hasMany(Finance::class);
    }

    public function rent()
    {
        return $this->hasOne(Apartment::class, 'apartment_id');
    }
}

app/Http/Controllers/ApartmentsController.php
<?php

namespace App\Http\Controllers;

use App\Apartment;
use App\Http\Requests\ApartamentCreateRequest;
use App\Note;
use App\Room;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ApartmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $apartments = Apartment::all()->where('owner_id', Auth::id());
        $rooms = Room::all();
        return view('apartments.index', compact('apartments', 'rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('apartments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ApartamentCreateRequest $request)
    {
        $img_1 = (isset($request->img_1) ? $request->img_1->store('apartments') : null);
        $img_2 = (isset($request->img_2) ? $request->img_2->store('apartments') : null);
        $img_3 = (isset($request->img_3) ? $request->img_3->store('apartments') : null);
        $img_4 = (isset($request->img_4) ? $request->img_4->store('apartments') : null);

        $owner_id = Auth::id();

        Apartment::create([
            'title' => $request->title,
            'owner_id' => $owner_id,
            'city' => $request->city,
            'street' => $request->street,
            'apartment_number' => $request->apartment_number,
            'number_of_beds' => $request->number_of_beds,
            'rental_price' => $request->rental_price,
            'fees' => $request->fees,
            'description' => $request->description,
            'img_1' => $img_1,
            'img_2' => $img_2,
            'img_3' => $img_3,
            'img_4' => $img_4,
        ]);


        return redirect()->route('apartments.index')
            ->with('success', 'Mieszkanie dodane pomyślnie.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Apartment $apartment)
    {
        $notes = Note::latest()->where('apartment_id', 2)->paginate(5);
        return view('apartments.show', compact('apartment', 'notes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Apartment $apartment)
    {
        return view('apartments.edit', compact('apartment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Apartment $apartment)
    {
        $imgs = ['img_1', 'img_2', 'img_3', 'img_4'];

        foreach ($imgs as $key => $img) {
            if ($request->hasFile($img)) {
                $apartment->deleteImage($apartment->$img);
                $imgs[$key] = $request->$img->store('apartments');
            } else {
                $imgs[$key] = $apartment->$img;
            }
        }

        $apartment->update([
            'title' => $request->title,
            'city' => $request->city,
            'street' => $request->street,
            'apartment_number' => $request->apartment_number,
            'number_of_beds' => $request->number_of_beds,
            'rental_price' => $request->rental_price,
            'fees' => $request->fees,
            'description' => $request->description,
            'img_1' => $imgs[0],
            'img_2' => $imgs[1],
            'img_3' => $imgs[2],
            'img_4' => $imgs[3],
        ]);

        return redirect()
            ->back()
            ->with('success', 'Mieszkanie poprawnie uaktualnione');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/apartments/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h5>dodawanie nowego mieszkania</h5>
                </div>
                <div class="card-body">
                    <form action="{{route('apartments.store')}}" method="post" enctype="multipart/form-data">
                        @csrf

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Tytuł</label>
                                <input type="text" class="form-control" id="title" name="title"
                                       value="{{ old('title') }}"
                                       placeholder="Słoneczne, przestronne mieszkanie dla 4 studentów">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-5 mb-3">
                                <label for="title">Miasto</label>
                                <input type="text" class="form-control" id="city" name="city"
                                       value="{{ old('city') }}"
                                       placeholder="Warszawa">
                            </div>
                            <div class="col-md-5 mb-3">
                                <label for="title">Ulica</label>
                                <input type="text" class="form-control" id="street" name="street"
                                       value="{{ old('street') }}"
                                       placeholder="Wielkopolska">
                            </div>
                            <div class="col-md-2 mb-3">
                                <label for="title">Numer budynku</label>
                                <input type="text" class="form-control" id="apartment_number" name="apartment_number"
                                       value="{{ old('apartment_number') }}"
                                       placeholder="4b">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-3 mb-3">
                                <label for="title">Ilość miejsc</label>
                                <input type="text" class="form-control" id="number_of_beds" name="number_of_beds"
                                       value="{{ old('number_of_beds') }}"
                                       placeholder="5">
                            </div>
                            <div class="col-md-4 offset-1 mb-3">
                                <label for="title">Cena za wynajem</label>
                                <input type="text" class="form-control" id="rental_price" name="rental_price"
                                       value="{{ old('rental_price') }}"
                                       placeholder="1300">
                            </div>
                            <div class="col-md-3 offset-1 mb-3">
                                <label for="title">Cena za media</label>
                                <input type="text" class="form-control" id="fees" name="fees"
                                       value="{{ old('fees') }}"
                                       placeholder="300">
                            </div>
                        </div>

                        <div>
                            <label for="title">Dodaj zdjęcia</label>

                            <div class="form-row mb-3">
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="img_1" id="img_1">
                                            <label class="custom-file-label" for="img_1">zdjęcie 1</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="img_2" id="img_2">
                                        <label class="custom-file-label" for="img_2">zdjęcie 2</label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-row mb-3">
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="img_3" id="img_3">
                                            <label class="custom-file-label" for="img_3">zdjęcie 3</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="img_4" id="img_4">
                                        <label class="custom-file-label" for="img_4">zdjęcie 4</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Opis</label>
                                <input id="description" type="hidden" name="description">
                                <trix-editor input="description">{!! old('description') !!}</trix-editor>
                            </div>
                        </div>

                        <div class="form-group text-center my-5">
                            <button class="btn btn-success btn-block" type="submit">dodaj mieszkanie</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/apartments/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h5>edytowanie mieszkania</h5>
                </div>
                <div class="card-body">
                    <form action="{{route('apartments.update', $apartment->id)}}" method="post"
                          enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Tytuł</label>
                                <input type="text" class="form-control" id="title" name="title"
                                       value="{{old('title') ?? $apartment->title}}">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-5 mb-3">
                                <label for="title">Miasto</label>
                                <input type="text" class="form-control" id="city" name="city"
                                       value="{{old('city') ?? $apartment->city}}">
                            </div>
                            <div class="col-md-5 mb-3">
                                <label for="title">Ulica</label>
                                <input type="text" class="form-control" id="street" name="street"
                                       value="{{old('street') ?? $apartment->street}}">
                            </div>
                            <div class="col-md-2 mb-3">
                                <label for="title">Numer budynku</label>
                                <input type="text" class="form-control" id="apartment_number" name="apartment_number"
                                       value="{{old('apartment_number') ?? $apartment->apartment_number}}">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-3 mb-3">
                                <label for="title">Ilość miejsc</label>
                                <input type="text" class="form-control" id="number_of_beds" name="number_of_beds"
                                       value="{{old('number_of_beds') ?? $apartment->number_of_beds}}">
                            </div>
                            <div class="col-md-4 offset-1 mb-3">
                                <label for="title">Cena za wynajem</label>
                                <input type="text" class="form-control" id="rental_price" name="rental_price"
                                       value="{{old('rental_price') ?? $apartment->rental_price}}">
                            </div>
                            <div class="col-md-3 offset-1 mb-3">
                                <label for="title">Cena za media</label>
                                <input type="text" class="form-control" id="fees" name="fees"
                                       value="{{old('fees') ?? $apartment->fees}}">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-12 mb-3">
                                <label for="title">Opis</label>
                                <input id="description" type="hidden" name="description">
                                <trix-editor
                                    input="description">{!! old('description') ?? $apartment->description !!}</trix-editor>
                            </div>
                        </div>

                        <div>
                            <label for="title">Dodaj zdjęcia</label>

                            <div class="form-row mb-3">
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="img_1" id="img_1">
                                            <label class="custom-file-label" for="img_1">zdjęcie 1</label>
                                        </div>
                                        @if($apartment->img_1)
                                            <div class="mt-5">
                                                <img src="{{ asset('storage/'. $apartment->img_1)}}" class="img-fluid">
                                            </div>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="img_2" id="img_2">
                                        <label class="custom-file-label" for="img_2">zdjęcie 2</label>
                                    </div>
                                    @if($apartment->img_2)
                                        <div class="mt-5">
                                            <img src="{{ asset('storage/'. $apartment->img_2)}}" class="img-fluid">
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-row mb-3">
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="img_3" id="img_3">
                                            <label class="custom-file-label" for="img_3">zdjęcie 3</label>
                                        </div>
                                        @if($apartment->img_3)
                                            <div class="mt-5">
                                                <img src="{{ asset('storage/'. $apartment->img_3)}}" class="img-fluid">
                                            </div>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="img_4" id="img_4">
                                        <label class="custom-file-label" for="img_4">zdjęcie 4</label>
                                    </div>
                                    @if($apartment->img_4)
                                        <div class="mt-5">
                                            <img src="{{ asset('storage/'. $apartment->img_4)}}" class="img-fluid">
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="form-group text-center my-5">
                            <button class="btn btn-success btn-block" type="submit">zapisz zmiany</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/apartments/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            @forelse($apartments as $apartment)
                <div
                    class="pl-2 no-gutters border flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="row">

                        <div class="col-7 p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block text-primary"><h4>{{$apartment->city}} {{$apartment->street}}</h4></strong>
                            <div class="text-muted small">{{$apartment->created_at}}</div>
                            <h4 class="mt-3">{{$apartment->title}}</h4>
                            <p class="card-text mb-auto">{!!  $apartment->description !!}</p>

                            <div class="btn-group">
                                <button type="button" class="btn btn-primary dropdown-toggle px-1" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
                                    menu
                                </button>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left">
                                    <a href="{{route('apartments.show', $apartment->id)}}">
                                        <button type="button" class="btn btn-primary">Finanse</button>
                                    </a>
                                    <a href="{{route('apartments.show', $apartment->id)}}">
                                        <button type="button" class="btn btn-success">Podgląd</button>
                                    </a>
                                    <a href="{{route('apartments.edit', $apartment->id)}}">
                                        <button type="button" class="btn btn-warning">Edytuj</button>
                                    </a>
                                    <a href="{{route('apartments.show', $apartment->id)}}">
                                        <button type="button" class="btn btn-danger">Zawieś</button>
                                    </a>
                                    <a href="{{route('rooms.create', $apartment->id)}}" class="">
                                        <button type="button" class="btn btn-primary">dodaj pokój</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-5 d-none d-lg-block">
                            <div class="mt-5 p-3">
                                <img src="{{ asset('storage/'. $apartment->img_1)}}" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            @endforelse
        </div>
    </div>
@endsection

resources/views/apartments/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            @include('note.notes')
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-12">
            <div class="card p-3 rounded shadow-sm">
                <div class="card-header">
                    <h6>Numer ogłoszenia: {{$apartment->id}}</h6>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <span>Tytuł:</span>
                            <span class="font-weight-bold">{{$apartment->title}}</span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between">
                            <span>
                                <span>Miasto:</span>
                                <span class="font-weight-bold">{{$apartment->city}}</span>
                            </span>
                            <span>
                                <span>Ulica:</span>
                                <span class="font-weight-bold">{{$apartment->street}}</span>
                            </span>
                            <span>
                                <span>Numer budynku:</span>
                                <span class="font-weight-bold">{{$apartment->apartment_number}}</span>
                            </span>
                        </li>

                        <li class="list-group-item d-flex justify-content-between">
                            <span>
                                <span>Ilość łóżek:</span>
                                <span class="font-weight-bold">{{$apartment->number_of_beds}}</span>
                            </span>
                            <span>
                                <span>Cena wynajmu (za całość):</span>
                                <span class="font-weight-bold">{{$apartment->rental_price}}</span>
                            </span>
                            <span>
                                <span>Opłaty:</span>
                                <span class="font-weight-bold">{{$apartment->fees}}</span>
                            </span>
                        </li>

                        <li class="list-group-item">
                            <span>Opis:</span>
                            <span class="font-weight-bold">{!! $apartment->description !!}</span>
                        </li>

                        <li class="list-group-item">
                            @if($apartment->img_2)
                                <div class="row">
                                    <div class="col-6">
                                        <div class="mt-5">
                                            <img src="{{ asset('storage/'. $apartment->img_1)}}" class="img-fluid">
                                        </div>
                                    </div>

                                    <div class="col-6">
                                        <div class="mt-5">
                                            <img src="{{ asset('storage/'. $apartment->img_2)}}" class="img-fluid">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-6">
                                        @if($apartment->img_3)
                                            <div class="mt-5">
                                                <img src="{{ asset('storage/'. $apartment->img_3)}}" class="img-fluid">
                                            </div>
                                        @endif
                                    </div>

                                    <div class="col-6">
                                        @if($apartment->img_4)
                                            <div class="mt-5">
                                                <img src="{{ asset('storage/'. $apartment->img_4)}}" class="img-fluid">
                                            </div>
                                        @endif
                                    </div>
                                </div>
                        </li>
                        @else
                            <div class="mt-5">
                                <img src="{{ asset('storage/'. $apartment->img_1)}}" class="img-fluid">
                            </div>
                        @endif

                        <li class="list-group-item">
                            <span>Dodano:</span>
                            <span class="font-weight-bold">{{ $apartment->created_at }}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection