routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
});

Auth::routes();

Route::resource('app', 'AppController');

Route::get('/search', 'SearchController@apartments')
    ->name('search');

Route::middleware(['auth', 'owner'])->group(function () {


    Route::resource('apartments', 'ApartmentsController');

    Route::resource('rooms', 'RoomsController');

    Route::get('rooms/create/{id?}', 'RoomsController@create')
        ->name('rooms.create');

    Route::resource('rent', 'RentController');

    Route::get('rent/create/{id}', 'RentController@create')
        ->name('rent.create');

    Route::resource('note', 'NoteController');

    Route::resource('finance', 'FinanceController');
});

Route::middleware(['auth'])->group(function () {
    Route::resource('home', 'HomeController');
    Route::resource('forum', 'ForumController');
    Route::get('forum/tenant/{id}', 'ForumController@tenant')
        ->name('forum.tenant');
});

resources/views/includes/info.blade.php
@if(session()->has('success'))
    <div class="alert alert-success">
        {{session()->get('success')}}
    </div>
@endif

@if(session()->has('error'))
    <div class="alert alert-danger">
        {{session()->get('error')}}
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/includes/nav.blade.php
<div class="col-md-3">

    <ul class="list-group text-center">
        <li class="list-group-item bg-light">
            <a href="{{route('home.index')}}">przegląd</a>
        </li>
    </ul>

    @if(!auth()->user()->isOwner())
        <ul class="list-group text-center mt-3">
            <li class="list-group-item bg-light">
                <a href="{{route('forum.tenant', \Illuminate\Support\Facades\Auth::id())}}">forum</a>
            </li>
        </ul>
    @endif


    @if(auth()->user()->isOwner())
        <ul class="list-group text-center mt-3">
            <li class="list-group-item bg-light">
                <a href="{{route('forum.index')}}">fora</a>
            </li>


            <li class="list-group-item bg-light">
                <a href="{{route('note.create')}}">notatki</a>
            </li>

            <li class="list-group-item bg-light">
                <a href="{{route('finance.index')}}">finanse</a>
            </li>
        </ul>

        <ul class="list-group text-center mt-3">


            <li class="list-group-item bg-light">
                <a href="{{route('apartments.index')}}">twoje mieszkania</a>
            </li>

            <li class="list-group-item bg-light">
                <a href="{{route('rooms.index')}}">twoje pokoje</a>
            </li>

        </ul>

        <ul class="list-group text-center mt-3">

            <li class="list-group-item bg-light">
                <a href="{{route('apartments.create')}}">dodaj nowe mieszkanie</a>
            </li>

            <li class="list-group-item bg-light">
                <a href="{{route('rent.index')}}">dodaj lokatora do mieszkania</a>
            </li>

        </ul>
    @endif


</div>